site_name: DevHub Documentation
site_description: The Swiss Army Knife for Developers
site_url: https://devhub-cli.readthedocs.io/
repo_url: https://github.com/username/devhub
repo_name: username/devhub
site_dir: ../site

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
    - Configuration: configuration.md
  - User Guide:
    - Code Formatting: user-guide/formatting.md
    - API Testing: user-guide/api.md
    - Git Tools: user-guide/git.md
    - Security: user-guide/security.md
    - Data Conversion: user-guide/data.md
    - System Monitoring: user-guide/system.md
  - Plugin Development:
    - Plugin Architecture: plugins/architecture.md
    - Creating Plugins: plugins/creating.md
    - Plugin API: plugins/api.md
    - Examples: plugins/examples.md
  - Reference:
    - CLI Reference: reference/cli.md
    - Configuration: reference/config.md
    - API Reference: reference/api.md
  - Contributing:
    - Contributing Guide: contributing.md
    - Development Setup: development.md
    - Testing: testing.md
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/username/devhub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/devhub_cli
    - icon: fontawesome/brands/discord
      link: https://discord.gg/devhub
  version:
    provider: mike

copyright: Copyright &copy; 2025 DevHub Team
