name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

env:
  PYTHON_VERSION: "3.11"

permissions:
  contents: write  # Needed for pushing to gh-pages branch

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for gh-deploy

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd docs
        mkdocs gh-deploy --force --clean --verbose
        
    - name: Check deployment status
      run: |
        echo "✅ Documentation deployment completed"
        echo "📄 If this is the first deployment, you need to:"
        echo "   1. Go to repository Settings → Pages"
        echo "   2. Set Source to 'Deploy from a branch'"
        echo "   3. Select branch 'gh-pages' and folder '/ (root)'"
        echo "   4. Click Save"
        echo "📚 Once configured, your docs will be available at:"
        echo "   https://arafat-mahmud.github.io/Developer-Utilities-Hub/"
