name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force publish (skip existing check)'
        required: false
        default: false
        type: boolean
      
permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Build package
        run: |
          echo "Building package..."
          python -m build
          echo "Package built successfully"
      
      - name: List built files
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Package verification:"
          python -m twine check dist/*
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          skip-existing: ${{ !inputs.force_publish }}
