name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment: release  # Defines a deployment environment for PyPI publishing
    permissions:
      id-token: write  # For trusted publishing

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Publish to PyPI
      if: success()
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
        verbose: true
        skip-existing: true  # Skip if version already exists on PyPI

    - name: Verify PyPI Release
      if: success()
      run: |
        echo "✅ Package successfully published to PyPI!"
        echo "📦 Check your package at: https://pypi.org/project/devhub-cli/"
        
    - name: Create PyPI Release Summary
      if: success()
      run: |
        echo "## 📦 DevHub CLI Package Published" > $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The package has been successfully published to PyPI." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Package Information:**" >> $GITHUB_STEP_SUMMARY
        echo "- **Name:** devhub-cli" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** $(python -c "import tomli; print(tomli.load(open('pyproject.toml', 'rb'))['project']['version'])")" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Installation Instructions:**" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "pip install devhub-cli" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
