name: Publish to PyPI

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - none
  
  # Automatic trigger on release
  release:
    types: [published]

permissions:
  contents: write
  id-token: write  # For trusted publishing to PyPI

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools wheel bump2version
      
      - name: Set Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Bump version if requested
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version_bump != 'none'
        run: |
          echo "Bumping ${{ github.event.inputs.version_bump }} version"
          bump2version ${{ github.event.inputs.version_bump }}
          git push --tags
          git push
      
      - name: Build package
        run: python -m build
      
      - name: Verify package
        run: twine check dist/*
      
      - name: Display package info
        run: |
          echo "📦 Publishing package to PyPI"
          echo "Package contents:"
          ls -la dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true
          skip-existing: true
